## Configuration file for Seminarski application.

# User login.
login: fikt
# User  password.
password: crimson

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: seminarski.keystore
          keyStorePassword: crimson
          validateCerts: false
          validatePeers: false

# Database settings.
database:
   # the name of the JDBC driver, mysql in our case
   driverClass: com.mysql.jdbc.Driver
   # the username
   user: root
   # the password
   password: pece123!
   # the JDBC URL
   url: jdbc:mysql://localhost:3306/testdb2

#API settings
#API URL
apiURL: https://openexchangerates.org/api/latest.json
#API key
apiKey: <Your API key>

#Jersey client settings
jerseyClient:
    #The maximum idle time for a connection, once established.
    timeout: 512ms
    #The size of the work queue of the pool used for asynchronous requests.
    #Additional threads will be spawn only if the queue is reached its maximum size.
    workQueueSize: 16

